//! Currency table: ISO 4217 fiat currencies, precious metals and popular crypto.

/// A currency known to the engine. Exchange rates come from a [`crate::RateProvider`].
#[derive(Debug)]
pub struct Currency {
    /// ISO code, e.g. "USD".
    pub code: &'static str,
    /// Symbol printed before amounts ("$5.00"); codes are printed after otherwise.
    pub symbol: Option<&'static str>,
    /// Digits after the decimal point in formatted amounts.
    pub decimals: u8,
    /// Extra spellings: lowercase names match case-insensitively and get a plural
    /// with "-s", others match exactly.
    pub aliases: &'static [&'static str],
    pub crypto: bool,
}

const fn fiat(code: &'static str, symbol: &'static str, decimals: u8, aliases: &'static [&'static str]) -> Currency {
    let symbol = if symbol.is_empty() { None } else { Some(symbol) };
    Currency { code, symbol, decimals, aliases, crypto: false }
}

const fn crypto(code: &'static str, aliases: &'static [&'static str]) -> Currency {
    Currency { code, symbol: None, decimals: 8, aliases, crypto: true }
}

/// Lowercase codes that are common English words or units, so only uppercase works.
pub const AMBIGUOUS_CODES: &[&str] = &[
    "all", "apt", "atom", "bam", "bob", "cup", "dash", "dot", "etc", "gel", "imp", "link", "mad", "mop", "near", "op",
    "pen", "sos", "ton", "top", "try", "uni",
];

#[rustfmt::skip]
pub static CURRENCIES: &[Currency] = &[
    // Most used first: ambiguous names resolve to the earliest entry.
    fiat("USD", "$", 2, &["US$", "dollar", "buck", "us dollar", "american dollar"]),
    fiat("EUR", "€", 2, &["€", "euro"]),
    fiat("GBP", "£", 2, &["£", "quid", "sterling", "pound sterling", "pounds sterling", "british pound"]),
    fiat("JPY", "¥", 0, &["¥", "JP¥", "円", "yen", "japanese yen"]),
    fiat("CNY", "CN¥", 2, &["CN¥", "元", "yuan", "renminbi", "rmb", "chinese yuan"]),
    fiat("CHF", "", 2, &["franc", "swiss franc"]),
    fiat("CAD", "C$", 2, &["C$", "CA$", "canadian dollar", "loonie"]),
    fiat("AUD", "A$", 2, &["A$", "AU$", "australian dollar", "aussie dollar"]),
    fiat("NZD", "NZ$", 2, &["NZ$", "new zealand dollar", "kiwi dollar"]),
    fiat("HKD", "HK$", 2, &["HK$", "hong kong dollar"]),
    fiat("SGD", "S$", 2, &["S$", "singapore dollar"]),
    fiat("TWD", "NT$", 2, &["NT$", "taiwan dollar", "new taiwan dollar", "NTD"]),
    fiat("INR", "₹", 2, &["₹", "Rs", "rupee", "indian rupee"]),
    fiat("RUB", "₽", 2, &["₽", "ruble", "rouble", "russian ruble", "russian rouble"]),
    fiat("KZT", "₸", 2, &["₸", "tenge", "kazakh tenge", "kazakhstani tenge"]),
    fiat("UAH", "₴", 2, &["₴", "hryvnia", "hryvnya", "ukrainian hryvnia"]),
    fiat("KRW", "₩", 0, &["₩", "korean won", "south korean won"]),
    fiat("ILS", "₪", 2, &["₪", "shekel", "sheqel", "israeli shekel", "nis", "new israeli shekel", "new israeli sheqel"]),
    fiat("TRY", "₺", 2, &["₺", "lira", "turkish lira", "TL"]),
    fiat("VND", "₫", 0, &["₫", "dong", "vietnamese dong"]),
    fiat("PHP", "₱", 2, &["₱", "philippine peso"]),
    fiat("NGN", "₦", 2, &["₦", "naira", "nigerian naira"]),
    fiat("THB", "฿", 2, &["฿", "baht", "thai baht"]),
    fiat("BRL", "R$", 2, &["R$", "reais", "brazilian real", "brazilian reais"]),
    fiat("MXN", "MX$", 2, &["MX$", "peso", "mexican peso"]),
    fiat("SEK", "", 2, &["krona", "kronor", "swedish krona", "swedish kronor"]),
    fiat("NOK", "", 2, &["krone", "kroner", "norwegian krone", "norwegian kroner"]),
    fiat("DKK", "", 2, &["danish krone", "danish kroner"]),
    fiat("PLN", "", 2, &["zł", "zloty", "złoty", "polish zloty"]),
    fiat("CZK", "", 2, &["Kč", "koruna", "czech koruna", "czech crown"]),
    fiat("HUF", "", 2, &["forint", "hungarian forint"]),
    fiat("RON", "", 2, &["leu", "lei", "romanian leu", "romanian lei"]),
    fiat("BGN", "", 2, &["lev", "leva", "bulgarian lev"]),
    fiat("ZAR", "", 2, &["rand", "south african rand"]),
    fiat("AED", "", 2, &["dirham", "uae dirham", "emirati dirham"]),
    fiat("SAR", "", 2, &["riyal", "saudi riyal"]),
    fiat("AFN", "", 2, &["afghani", "afghan afghani"]),
    fiat("ALL", "", 2, &["lek", "albanian lek"]),
    fiat("AMD", "", 2, &["֏", "dram", "armenian dram"]),
    fiat("ANG", "", 2, &["netherlands antillean guilder"]),
    fiat("AOA", "", 2, &["kwanza", "angolan kwanza"]),
    fiat("ARS", "", 2, &["argentine peso"]),
    fiat("AWG", "", 2, &["aruban florin"]),
    fiat("AZN", "", 2, &["₼", "manat", "azerbaijani manat"]),
    fiat("BAM", "", 2, &["convertible mark", "bosnia and herzegovina convertible mark"]),
    fiat("BBD", "", 2, &["barbadian dollar", "barbados dollar"]),
    fiat("BDT", "", 2, &["৳", "taka", "bangladeshi taka"]),
    fiat("BHD", "", 3, &["bahraini dinar"]),
    fiat("BIF", "", 0, &["burundian franc", "burundi franc"]),
    fiat("BMD", "", 2, &["bermudian dollar"]),
    fiat("BND", "", 2, &["brunei dollar"]),
    fiat("BOB", "", 2, &["boliviano", "bolivian boliviano"]),
    fiat("BSD", "", 2, &["bahamian dollar"]),
    fiat("BTN", "", 2, &["ngultrum", "bhutanese ngultrum"]),
    fiat("BWP", "", 2, &["pula", "botswana pula"]),
    fiat("BYN", "", 2, &["belarusian ruble", "belarusian rouble"]),
    fiat("BZD", "", 2, &["belize dollar"]),
    fiat("CDF", "", 2, &["congolese franc"]),
    fiat("CLP", "", 0, &["chilean peso"]),
    fiat("COP", "", 2, &["colombian peso"]),
    fiat("CRC", "", 2, &["₡", "colon", "colón", "costa rican colon"]),
    fiat("CUP", "", 2, &["cuban peso"]),
    fiat("CVE", "", 2, &["cape verdean escudo", "escudo", "cape verde escudo"]),
    fiat("DJF", "", 0, &["djiboutian franc", "djibouti franc"]),
    fiat("DOP", "", 2, &["dominican peso"]),
    fiat("DZD", "", 2, &["algerian dinar"]),
    fiat("EGP", "", 2, &["egyptian pound"]),
    fiat("ERN", "", 2, &["nakfa"]),
    fiat("ETB", "", 2, &["birr", "ethiopian birr"]),
    fiat("FJD", "", 2, &["fijian dollar", "fiji dollar"]),
    fiat("FKP", "", 2, &["falkland islands pound"]),
    fiat("GEL", "", 2, &["₾", "lari", "georgian lari"]),
    fiat("GHS", "", 2, &["₵", "cedi", "ghanaian cedi", "ghana cedi"]),
    fiat("GIP", "", 2, &["gibraltar pound"]),
    fiat("GMD", "", 2, &["dalasi", "gambian dalasi"]),
    fiat("GNF", "", 0, &["guinean franc", "guinea franc"]),
    fiat("GTQ", "", 2, &["quetzal", "quetzales", "guatemalan quetzal", "guatemalan quetzales"]),
    fiat("GYD", "", 2, &["guyanese dollar", "guyana dollar"]),
    fiat("HNL", "", 2, &["lempira", "honduran lempira"]),
    fiat("HTG", "", 2, &["gourde", "haitian gourde"]),
    fiat("IDR", "", 2, &["Rp", "rupiah", "indonesian rupiah"]),
    fiat("IQD", "", 3, &["iraqi dinar"]),
    fiat("IRR", "", 2, &["iranian rial"]),
    fiat("ISK", "", 0, &["icelandic krona", "icelandic kronur", "iceland krona"]),
    fiat("JMD", "", 2, &["jamaican dollar"]),
    fiat("JOD", "", 3, &["jordanian dinar"]),
    fiat("KES", "", 2, &["KSh", "kenyan shilling"]),
    fiat("KGS", "", 2, &["som", "kyrgyz som", "kyrgyzstani som"]),
    fiat("KHR", "", 2, &["riel", "cambodian riel"]),
    fiat("KMF", "", 0, &["comorian franc"]),
    fiat("KPW", "", 2, &["north korean won"]),
    fiat("KWD", "", 3, &["kuwaiti dinar"]),
    fiat("KYD", "", 2, &["cayman islands dollar"]),
    fiat("LAK", "", 2, &["₭", "kip", "lao kip"]),
    fiat("LBP", "", 2, &["lebanese pound"]),
    fiat("LKR", "", 2, &["sri lankan rupee", "sri lanka rupee"]),
    fiat("LRD", "", 2, &["liberian dollar"]),
    fiat("LSL", "", 2, &["loti", "maloti", "lesotho loti", "lesotho maloti"]),
    fiat("LYD", "", 3, &["libyan dinar"]),
    fiat("MAD", "", 2, &["moroccan dirham"]),
    fiat("MDL", "", 2, &["moldovan leu", "moldovan lei"]),
    fiat("MGA", "", 2, &["ariary", "malagasy ariary"]),
    fiat("MKD", "", 2, &["denar", "macedonian denar", "denari", "macedonian denari"]),
    fiat("MMK", "", 2, &["kyat", "myanmar kyat"]),
    fiat("MNT", "", 2, &["₮", "tugrik", "mongolian tugrik", "togrog", "tögrög", "mongolian togrog", "mongolian tögrög"]),
    fiat("MOP", "", 2, &["pataca", "macanese pataca"]),
    fiat("MRU", "", 2, &["ouguiya", "mauritanian ouguiya"]),
    fiat("MUR", "", 2, &["mauritian rupee", "mauritius rupee"]),
    fiat("MVR", "", 2, &["rufiyaa", "maldivian rufiyaa"]),
    fiat("MWK", "", 2, &["malawian kwacha"]),
    fiat("MYR", "", 2, &["RM", "ringgit", "malaysian ringgit"]),
    fiat("MZN", "", 2, &["metical", "mozambican metical"]),
    fiat("NAD", "", 2, &["namibian dollar", "namibia dollar"]),
    fiat("NIO", "", 2, &["cordoba", "córdoba", "nicaraguan cordoba"]),
    fiat("NPR", "", 2, &["nepalese rupee", "nepali rupee"]),
    fiat("OMR", "", 3, &["omani rial"]),
    fiat("PAB", "", 2, &["balboa", "panamanian balboa"]),
    fiat("PEN", "", 2, &["soles", "peruvian sol", "peruvian soles"]),
    fiat("PGK", "", 2, &["kina", "papua new guinean kina"]),
    fiat("PKR", "", 2, &["pakistani rupee", "pakistan rupee"]),
    fiat("PYG", "", 0, &["guarani", "paraguayan guarani", "guaraní", "paraguayan guaraní"]),
    fiat("QAR", "", 2, &["qatari riyal"]),
    fiat("RSD", "", 2, &["serbian dinar"]),
    fiat("RWF", "", 0, &["rwandan franc", "rwanda franc"]),
    fiat("SBD", "", 2, &["solomon islands dollar"]),
    fiat("SCR", "", 2, &["seychellois rupee", "seychelles rupee"]),
    fiat("SDG", "", 2, &["sudanese pound"]),
    fiat("SHP", "", 2, &["saint helena pound", "st helena pound"]),
    fiat("SLE", "", 2, &["leone", "sierra leonean leone"]),
    fiat("SOS", "", 2, &["somali shilling"]),
    fiat("SRD", "", 2, &["surinamese dollar"]),
    fiat("SSP", "", 2, &["south sudanese pound"]),
    fiat("STN", "", 2, &["dobra", "são tomé and príncipe dobra"]),
    fiat("SVC", "", 2, &["salvadoran colon", "el salvador colon"]),
    fiat("SYP", "", 2, &["syrian pound"]),
    fiat("SZL", "", 2, &["lilangeni", "emalangeni", "swazi lilangeni", "swazi emalangeni"]),
    fiat("TJS", "", 2, &["somoni", "tajikistani somoni"]),
    fiat("TMT", "", 2, &["turkmen manat", "turkmenistani manat"]),
    fiat("TND", "", 3, &["tunisian dinar"]),
    fiat("TOP", "", 2, &["paanga", "pa'anga"]),
    fiat("TTD", "", 2, &["trinidad and tobago dollar"]),
    fiat("TZS", "", 2, &["tanzanian shilling"]),
    fiat("UGX", "", 0, &["ugandan shilling"]),
    fiat("UYU", "", 2, &["uruguayan peso"]),
    fiat("UZS", "", 2, &["uzbek som", "uzbekistani som", "uzbekistan som"]),
    fiat("VES", "", 2, &["bolivar", "bolívar", "venezuelan bolivar", "venezuelan bolívar"]),
    fiat("VUV", "", 0, &["vatu", "vanuatu vatu"]),
    fiat("WST", "", 2, &["tala", "samoan tala"]),
    fiat("XAF", "", 0, &["cfa franc", "central african cfa franc"]),
    fiat("XCD", "", 2, &["east caribbean dollar"]),
    fiat("XOF", "", 0, &["west african cfa franc"]),
    fiat("XPF", "", 0, &["cfp franc"]),
    fiat("YER", "", 2, &["yemeni rial"]),
    fiat("ZMW", "", 2, &["zambian kwacha"]),
    // Precious metals, priced per troy ounce.
    fiat("XAU", "", 4, &[]),
    fiat("XAG", "", 4, &[]),
    fiat("XPT", "", 4, &[]),
    fiat("XPD", "", 4, &[]),
    crypto("BTC", &["₿", "XBT", "bitcoin"]),
    crypto("ETH", &["ether", "ethereum"]),
    crypto("USDT", &["tether"]),
    crypto("USDC", &[]),
    crypto("BNB", &["binance coin"]),
    crypto("SOL", &["solana"]),
    crypto("XRP", &["ripple"]),
    crypto("DOGE", &["dogecoin"]),
    crypto("ADA", &["cardano"]),
    crypto("TRX", &["tron"]),
    crypto("TON", &["toncoin"]),
    crypto("LTC", &["litecoin"]),
    crypto("BCH", &["bitcoin cash"]),
    crypto("DOT", &["polkadot"]),
    crypto("LINK", &["chainlink"]),
    crypto("XLM", &["stellar", "lumens"]),
    crypto("XMR", &["monero"]),
    crypto("AVAX", &["avalanche"]),
    crypto("SHIB", &["shiba inu"]),
    crypto("ATOM", &["cosmos"]),
    crypto("ETC", &["ethereum classic"]),
    crypto("POL", &["MATIC", "polygon"]),
    crypto("NEAR", &[]),
    crypto("UNI", &["uniswap"]),
    crypto("DAI", &[]),
    crypto("APT", &["aptos"]),
    crypto("ARB", &["arbitrum"]),
    crypto("OP", &["optimism"]),
    crypto("SUI", &[]),
    crypto("PEPE", &[]),
    crypto("HBAR", &["hedera"]),
    crypto("FIL", &["filecoin"]),
    crypto("ICP", &[]),
    crypto("BSV", &["bitcoin sv"]),
    crypto("DASH", &[]),
    crypto("NEO", &[]),
    crypto("LUNA", &[]),
];

/// The smallest unit of a currency, worth 10^-decimals of it: (code, name, plural, aliases).
pub static MINOR_UNITS: &[(&str, &str, &str, &[&str])] = &[
    ("USD", "cent", "cents", &["¢"]),
    ("EUR", "euro cent", "euro cents", &[]),
    ("GBP", "penny", "pence", &["pennies"]),
    ("BTC", "satoshi", "satoshis", &["sats"]),
];

/// Finds a currency by its ISO code (case-insensitive).
pub fn find(code: &str) -> Option<&'static Currency> {
    CURRENCIES.iter().find(|c| c.code.eq_ignore_ascii_case(code))
}
