//! Currency table: ISO 4217 fiat currencies, precious metals and popular crypto.

/// A currency known to the engine. Exchange rates come from a [`crate::RateProvider`].
#[derive(Debug)]
pub struct Currency {
    /// ISO code, e.g. "USD".
    pub code: &'static str,
    /// Symbol printed before amounts ("$5.00"); codes are printed after otherwise.
    pub symbol: Option<&'static str>,
    /// Digits after the decimal point in formatted amounts.
    pub decimals: u8,
    /// Extra spellings: lowercase names match case-insensitively, others exactly.
    pub aliases: &'static [&'static str],
    pub crypto: bool,
}

const fn fiat(code: &'static str, symbol: &'static str, decimals: u8, aliases: &'static [&'static str]) -> Currency {
    let symbol = if symbol.is_empty() { None } else { Some(symbol) };
    Currency { code, symbol, decimals, aliases, crypto: false }
}

const fn crypto(code: &'static str, aliases: &'static [&'static str]) -> Currency {
    Currency { code, symbol: None, decimals: 8, aliases, crypto: true }
}

/// Lowercase codes that are common English words or units, so only uppercase works.
pub const AMBIGUOUS_CODES: &[&str] = &[
    "all", "apt", "atom", "bam", "bob", "cup", "dot", "etc", "gel", "imp", "link", "mad", "mop", "near", "op", "pen",
    "sos", "ton", "top", "try", "uni",
];

#[rustfmt::skip]
pub static CURRENCIES: &[Currency] = &[
    // Most used first: ambiguous names resolve to the earliest entry.
    fiat("USD", "$", 2, &["US$", "USD$", "dollar", "dollars", "buck", "bucks", "us dollar", "us dollars", "american dollar", "american dollars"]),
    fiat("EUR", "€", 2, &["€", "euro", "euros"]),
    fiat("GBP", "£", 2, &["£", "quid", "sterling", "pound sterling", "pounds sterling", "british pound", "british pounds"]),
    fiat("JPY", "¥", 0, &["¥", "JP¥", "円", "yen", "japanese yen"]),
    fiat("CNY", "CN¥", 2, &["CN¥", "元", "yuan", "renminbi", "rmb", "chinese yuan"]),
    fiat("CHF", "", 2, &["franc", "francs", "swiss franc", "swiss francs"]),
    fiat("CAD", "C$", 2, &["C$", "CA$", "canadian dollar", "canadian dollars", "loonie", "loonies"]),
    fiat("AUD", "A$", 2, &["A$", "AU$", "australian dollar", "australian dollars"]),
    fiat("NZD", "NZ$", 2, &["NZ$", "new zealand dollar", "new zealand dollars"]),
    fiat("HKD", "HK$", 2, &["HK$", "hong kong dollar", "hong kong dollars"]),
    fiat("SGD", "S$", 2, &["S$", "singapore dollar", "singapore dollars"]),
    fiat("TWD", "NT$", 2, &["NT$", "taiwan dollar", "taiwan dollars", "new taiwan dollar", "new taiwan dollars"]),
    fiat("INR", "₹", 2, &["₹", "Rs", "rupee", "rupees", "indian rupee", "indian rupees"]),
    fiat("RUB", "₽", 2, &["₽", "ruble", "rubles", "rouble", "roubles", "russian ruble", "russian rubles", "russian rouble", "russian roubles"]),
    fiat("KZT", "₸", 2, &["₸", "tenge", "kazakh tenge", "kazakhstani tenge"]),
    fiat("UAH", "₴", 2, &["₴", "hryvnia", "hryvnias", "hryvnya", "ukrainian hryvnia"]),
    fiat("KRW", "₩", 0, &["₩", "korean won", "south korean won"]),
    fiat("ILS", "₪", 2, &["₪", "shekel", "shekels", "sheqel", "israeli shekel", "israeli shekels", "nis"]),
    fiat("TRY", "₺", 2, &["₺", "lira", "liras", "turkish lira"]),
    fiat("VND", "₫", 0, &["₫", "dong", "vietnamese dong"]),
    fiat("PHP", "₱", 2, &["₱", "philippine peso", "philippine pesos"]),
    fiat("NGN", "₦", 2, &["₦", "naira", "nigerian naira"]),
    fiat("THB", "฿", 2, &["฿", "baht", "thai baht"]),
    fiat("BRL", "R$", 2, &["R$", "reais", "brazilian real", "brazilian reais"]),
    fiat("MXN", "MX$", 2, &["MX$", "peso", "pesos", "mexican peso", "mexican pesos"]),
    fiat("SEK", "", 2, &["krona", "kronor", "swedish krona", "swedish kronor"]),
    fiat("NOK", "", 2, &["krone", "kroner", "norwegian krone", "norwegian kroner"]),
    fiat("DKK", "", 2, &["danish krone", "danish kroner"]),
    fiat("PLN", "", 2, &["zł", "zloty", "zlotys", "złoty", "polish zloty"]),
    fiat("CZK", "", 2, &["Kč", "koruna", "czech koruna", "czech crown", "czech crowns"]),
    fiat("HUF", "", 2, &["forint", "forints", "hungarian forint"]),
    fiat("RON", "", 2, &["leu", "lei", "romanian leu"]),
    fiat("BGN", "", 2, &["lev", "leva", "bulgarian lev"]),
    fiat("ZAR", "", 2, &["rand", "rands", "south african rand"]),
    fiat("AED", "", 2, &["dirham", "dirhams", "uae dirham", "emirati dirham"]),
    fiat("SAR", "", 2, &["riyal", "riyals", "saudi riyal", "saudi riyals"]),
    fiat("AFN", "", 2, &["afghani", "afghanis"]),
    fiat("ALL", "", 2, &["lek", "albanian lek"]),
    fiat("AMD", "", 2, &["֏", "dram", "drams", "armenian dram"]),
    fiat("ANG", "", 2, &["netherlands antillean guilder"]),
    fiat("AOA", "", 2, &["kwanza", "angolan kwanza"]),
    fiat("ARS", "", 2, &["argentine peso", "argentine pesos"]),
    fiat("AWG", "", 2, &["aruban florin"]),
    fiat("AZN", "", 2, &["₼", "manat", "azerbaijani manat"]),
    fiat("BAM", "", 2, &["convertible mark"]),
    fiat("BBD", "", 2, &["barbadian dollar", "barbados dollar"]),
    fiat("BDT", "", 2, &["৳", "taka", "bangladeshi taka"]),
    fiat("BHD", "", 3, &["bahraini dinar"]),
    fiat("BIF", "", 0, &["burundian franc"]),
    fiat("BMD", "", 2, &["bermudian dollar"]),
    fiat("BND", "", 2, &["brunei dollar"]),
    fiat("BOB", "", 2, &["boliviano", "bolivianos"]),
    fiat("BSD", "", 2, &["bahamian dollar"]),
    fiat("BTN", "", 2, &["ngultrum"]),
    fiat("BWP", "", 2, &["pula", "botswana pula"]),
    fiat("BYN", "", 2, &["belarusian ruble", "belarusian rubles", "belarusian rouble"]),
    fiat("BZD", "", 2, &["belize dollar"]),
    fiat("CDF", "", 2, &["congolese franc"]),
    fiat("CLP", "", 0, &["chilean peso", "chilean pesos"]),
    fiat("COP", "", 2, &["colombian peso", "colombian pesos"]),
    fiat("CRC", "", 2, &["₡", "colon", "colón", "costa rican colon"]),
    fiat("CUP", "", 2, &["cuban peso"]),
    fiat("CVE", "", 2, &["cape verdean escudo"]),
    fiat("DJF", "", 0, &["djiboutian franc"]),
    fiat("DOP", "", 2, &["dominican peso"]),
    fiat("DZD", "", 2, &["algerian dinar"]),
    fiat("EGP", "", 2, &["egyptian pound", "egyptian pounds"]),
    fiat("ERN", "", 2, &["nakfa"]),
    fiat("ETB", "", 2, &["birr", "ethiopian birr"]),
    fiat("FJD", "", 2, &["fijian dollar"]),
    fiat("FKP", "", 2, &["falkland islands pound"]),
    fiat("GEL", "", 2, &["₾", "lari", "georgian lari"]),
    fiat("GHS", "", 2, &["₵", "cedi", "cedis", "ghanaian cedi"]),
    fiat("GIP", "", 2, &["gibraltar pound"]),
    fiat("GMD", "", 2, &["dalasi"]),
    fiat("GNF", "", 0, &["guinean franc"]),
    fiat("GTQ", "", 2, &["quetzal", "quetzales"]),
    fiat("GYD", "", 2, &["guyanese dollar"]),
    fiat("HNL", "", 2, &["lempira"]),
    fiat("HTG", "", 2, &["gourde"]),
    fiat("IDR", "", 2, &["Rp", "rupiah", "indonesian rupiah"]),
    fiat("IQD", "", 3, &["iraqi dinar"]),
    fiat("IRR", "", 2, &["iranian rial"]),
    fiat("ISK", "", 0, &["icelandic krona", "icelandic kronur"]),
    fiat("JMD", "", 2, &["jamaican dollar"]),
    fiat("JOD", "", 3, &["jordanian dinar"]),
    fiat("KES", "", 2, &["KSh", "kenyan shilling", "kenyan shillings"]),
    fiat("KGS", "", 2, &["som", "kyrgyz som"]),
    fiat("KHR", "", 2, &["riel", "cambodian riel"]),
    fiat("KMF", "", 0, &["comorian franc"]),
    fiat("KPW", "", 2, &["north korean won"]),
    fiat("KWD", "", 3, &["kuwaiti dinar"]),
    fiat("KYD", "", 2, &["cayman islands dollar"]),
    fiat("LAK", "", 2, &["₭", "kip", "lao kip"]),
    fiat("LBP", "", 2, &["lebanese pound"]),
    fiat("LKR", "", 2, &["sri lankan rupee", "sri lankan rupees"]),
    fiat("LRD", "", 2, &["liberian dollar"]),
    fiat("LSL", "", 2, &["loti"]),
    fiat("LYD", "", 3, &["libyan dinar"]),
    fiat("MAD", "", 2, &["moroccan dirham"]),
    fiat("MDL", "", 2, &["moldovan leu"]),
    fiat("MGA", "", 2, &["ariary", "malagasy ariary"]),
    fiat("MKD", "", 2, &["denar", "macedonian denar"]),
    fiat("MMK", "", 2, &["kyat", "myanmar kyat"]),
    fiat("MNT", "", 2, &["₮", "tugrik", "mongolian tugrik"]),
    fiat("MOP", "", 2, &["pataca"]),
    fiat("MRU", "", 2, &["ouguiya"]),
    fiat("MUR", "", 2, &["mauritian rupee"]),
    fiat("MVR", "", 2, &["rufiyaa"]),
    fiat("MWK", "", 2, &["malawian kwacha"]),
    fiat("MYR", "", 2, &["RM", "ringgit", "malaysian ringgit"]),
    fiat("MZN", "", 2, &["metical", "mozambican metical"]),
    fiat("NAD", "", 2, &["namibian dollar"]),
    fiat("NIO", "", 2, &["cordoba", "córdoba", "nicaraguan cordoba"]),
    fiat("NPR", "", 2, &["nepalese rupee", "nepali rupee"]),
    fiat("OMR", "", 3, &["omani rial"]),
    fiat("PAB", "", 2, &["balboa"]),
    fiat("PEN", "", 2, &["soles", "peruvian sol"]),
    fiat("PGK", "", 2, &["kina"]),
    fiat("PKR", "", 2, &["pakistani rupee", "pakistani rupees"]),
    fiat("PYG", "", 0, &["guarani", "paraguayan guarani"]),
    fiat("QAR", "", 2, &["qatari riyal"]),
    fiat("RSD", "", 2, &["serbian dinar"]),
    fiat("RWF", "", 0, &["rwandan franc"]),
    fiat("SBD", "", 2, &["solomon islands dollar"]),
    fiat("SCR", "", 2, &["seychellois rupee"]),
    fiat("SDG", "", 2, &["sudanese pound"]),
    fiat("SHP", "", 2, &["saint helena pound"]),
    fiat("SLE", "", 2, &["leone"]),
    fiat("SOS", "", 2, &["somali shilling"]),
    fiat("SRD", "", 2, &["surinamese dollar"]),
    fiat("SSP", "", 2, &["south sudanese pound"]),
    fiat("STN", "", 2, &["dobra"]),
    fiat("SYP", "", 2, &["syrian pound"]),
    fiat("SZL", "", 2, &["lilangeni"]),
    fiat("TJS", "", 2, &["somoni"]),
    fiat("TMT", "", 2, &["turkmen manat"]),
    fiat("TND", "", 3, &["tunisian dinar"]),
    fiat("TOP", "", 2, &["paanga", "pa'anga"]),
    fiat("TTD", "", 2, &["trinidad and tobago dollar"]),
    fiat("TZS", "", 2, &["tanzanian shilling"]),
    fiat("UGX", "", 0, &["ugandan shilling"]),
    fiat("UYU", "", 2, &["uruguayan peso"]),
    fiat("UZS", "", 2, &["uzbek som", "uzbekistani som"]),
    fiat("VES", "", 2, &["bolivar", "bolívar", "venezuelan bolivar"]),
    fiat("VUV", "", 0, &["vatu"]),
    fiat("WST", "", 2, &["tala"]),
    fiat("XAF", "", 0, &["cfa franc", "central african cfa franc"]),
    fiat("XCD", "", 2, &["east caribbean dollar"]),
    fiat("XOF", "", 0, &["west african cfa franc"]),
    fiat("XPF", "", 0, &["cfp franc"]),
    fiat("YER", "", 2, &["yemeni rial"]),
    fiat("ZMW", "", 2, &["zambian kwacha"]),
    // Precious metals, priced per troy ounce.
    fiat("XAU", "", 4, &[]),
    fiat("XAG", "", 4, &[]),
    fiat("XPT", "", 4, &[]),
    fiat("XPD", "", 4, &[]),
    crypto("BTC", &["₿", "XBT", "bitcoin", "bitcoins"]),
    crypto("ETH", &["ether", "ethereum"]),
    crypto("USDT", &["tether"]),
    crypto("USDC", &[]),
    crypto("BNB", &[]),
    crypto("SOL", &["solana"]),
    crypto("XRP", &["ripple"]),
    crypto("DOGE", &["dogecoin"]),
    crypto("ADA", &["cardano"]),
    crypto("TRX", &["tron"]),
    crypto("TON", &["toncoin"]),
    crypto("LTC", &["litecoin", "litecoins"]),
    crypto("BCH", &["bitcoin cash"]),
    crypto("DOT", &["polkadot"]),
    crypto("LINK", &["chainlink"]),
    crypto("XLM", &["stellar", "lumens"]),
    crypto("XMR", &["monero"]),
    crypto("AVAX", &["avalanche"]),
    crypto("SHIB", &["shiba inu"]),
    crypto("ATOM", &["cosmos"]),
    crypto("ETC", &["ethereum classic"]),
    crypto("POL", &["MATIC", "polygon"]),
    crypto("NEAR", &[]),
    crypto("UNI", &["uniswap"]),
    crypto("DAI", &[]),
    crypto("APT", &["aptos"]),
    crypto("ARB", &["arbitrum"]),
    crypto("OP", &["optimism"]),
    crypto("SUI", &[]),
    crypto("PEPE", &[]),
    crypto("HBAR", &["hedera"]),
    crypto("FIL", &["filecoin"]),
    crypto("ICP", &[]),
];

/// Finds a currency by its ISO code (case-insensitive).
pub fn find(code: &str) -> Option<&'static Currency> {
    CURRENCIES.iter().find(|c| c.code.eq_ignore_ascii_case(code))
}
