#!/usr/bin/env python3
"""Builds crates/rechenkern/src/zones/cities.txt from GeoNames.

Usage: scripts/cities.py cities15000.txt wordlist.txt > crates/rechenkern/src/zones/cities.txt

- cities15000.txt: https://download.geonames.org/export/dump/cities15000.zip
- wordlist.txt: English words, e.g. share/dict/wamerican.35 from nixpkgs#scowl
"""

import re
import sys

# Alternate names are added only for big cities, to keep the file small.
ALTERNATES_FROM = 500_000
# Cities named like an English word must be this big to count ("Reading" yes, "Time" no).
WORD_NAMES_FROM = 200_000
# Words too common in calculations to ever mean a city.
STOPWORDS = {"sale", "man", "gold", "hub", "bush", "delta", "mango", "lion", "shaping", "lander", "terminus"}

ASCII = re.compile(r"^[A-Za-z' .-]+$")


def key(name):
    return " ".join(name.lower().replace("-", " ").split())


def main(cities_path, words_path):
    words = {w.strip().lower() for w in open(words_path, encoding="latin-1") if w.strip().isalpha()}
    best = {}  # key -> (population, zone)
    for line in open(cities_path, encoding="utf-8"):
        fields = line.rstrip("\n").split("\t")
        name, ascii_name, alternates, zone = fields[1], fields[2], fields[3], fields[17]
        population = int(fields[14] or 0)
        if not zone:
            continue
        names = {key(name), key(ascii_name)}
        if population < WORD_NAMES_FROM:
            names -= words
        if population >= ALTERNATES_FROM:
            for alt in alternates.split(","):
                # Skip airport codes like "OZH" and alternates that are words ("Deli" for Delhi).
                if ASCII.match(alt) and not (alt.isupper() and len(alt) <= 4) and key(alt) not in words:
                    names.add(key(alt))
        for n in names:
            if len(n) < 3 or n in STOPWORDS:
                continue
            # The most populous place wins a shared name.
            if n not in best or best[n][0] < population:
                best[n] = (population, zone)

    print("# City name -> IANA time zone, sorted by name for binary search.")
    print("# Generated by scripts/cities.py from GeoNames cities15000 (https://www.geonames.org),")
    print("# licensed under CC BY 4.0. Do not edit by hand.")
    for n in sorted(best, key=lambda s: s.encode("utf-8")):
        print(f"{n}\t{best[n][1]}")


if __name__ == "__main__":
    main(*sys.argv[1:3])
